import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.EN]: {
    title: "CODE 2 PROJECT",
    subtitle: "Turn single files into production-ready apps instantly.",
    dragDrop: "DROP SOURCE FILE",
    orSelect: "[ CLICK TO SCAN ]",
    analyzing: "ANALYZING...",
    generate: "INITIALIZE BUILD",
    detectedDeps: "MODULES",
    noDeps: "NO MODULES DETECTED",
    projectName: "PROJECT ID",
    downloading: "COMPRESSING...",
    success: "BUILD COMPLETE",
    aboutTitle: "SYSTEM ARCHITECTURE",
    aboutDesc: "Secure, client-side offline execution environment.",
    techStack: "SUPPORTED FORMATS",
    whyVite: "CORE ENGINE",
    whyViteDesc: "Powered by Vite for instant HMR and zero-config deployment.",
    howToRun: "EXECUTION PROTOCOL",
    step1: "Extract Archive",
    step2: "npm install",
    step3: "npm run dev",
    footer: "",
    pasteCode: "// Paste source code here...",
    tabUpload: "UPLOAD SOURCE",
    tabPaste: "RAW INPUT",
    processing: "PROCESSING...",
  },
  [Language.FA]: {
    title: "تبدیل کد به پروژه",
    subtitle: "تبدیل آنی فایل‌های خام به اپلیکیشن‌های مدرن",
    dragDrop: "فایل را رها کنید",
    orSelect: "[ انتخاب فایل ]",
    analyzing: "تحلیل وابستگی...",
    generate: "آغاز ساخت پروژه",
    detectedDeps: "ماژول‌ها",
    noDeps: "ماژولی یافت نشد",
    projectName: "شناسه پروژه",
    downloading: "فشرده‌سازی...",
    success: "ساخت موفقیت‌آمیز بود",
    aboutTitle: "معماری سیستم",
    aboutDesc: "محیط اجرای امن و آفلاین تحت مرورگر.",
    techStack: "فرمت‌های پشتیبانی شده",
    whyVite: "موتور اجرایی",
    whyViteDesc: "استفاده از هسته Vite برای سرعت بیلد بالا.",
    howToRun: "راهنمای اجرا",
    step1: "استخراج فایل",
    step2: "npm install",
    step3: "npm run dev",
    footer: "",
    pasteCode: "// کد منبع را اینجا وارد کنید...",
    tabUpload: "آپلود فایل",
    tabPaste: "ورودی دستی",
    processing: "در حال پردازش...",
  }
};